# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_OpQESoeOwHydam2d1Q_uJbZLmv1I9uQ
"""

# L = Linha
# C = Coluna
# -1 = bomba
# posi = variavel p/ linha i sorteada
# posj = variavel p/ guardar linha j sorteada
# posijogador = posijogador = int
#  posjjogador = variavel para guardar posição coluna j do jogador.
import random

def campo(tamanho):
  matriz = [[0] * tamanho] * tamanho
  return matriz

def minas(tamanho, qtde):
  matriz = campo(tamanho)
  # Implementar as minas no campo

  return matriz
  


def play():
  matriz = minas(9, 3)
  c = 1
  for Linhas in matriz:
    print(c, "|")
    l = 1
    for Colunas in Linhas:
      print (" 0 " , end="")
      l += 1
    c += 1
    print()

play()



while (bomba < 0 and bomba > (9*9)):
    print("%d",bomba)
  posi = int
  posj = int
  while (bomba > 0):
    posi = random() % 9;
    posij = random() % 9;
    if (matriz[posi][posij] == 0):
      matriz[posi][posij] = -1;
      bomba()
  vida = 1
  pontos = 0
  posijogador = int
  posjjogador = int
  while (vida == 1):
    print("Pontos: %d" % pontos)